### ISSUE TITLE
SDDP.jl, JuMP 0.19, and Julia 1.0

### ISSUE THREAD

**Issue by odow** [andrewrosemberg/HydroPowerModels.jl#3]
The new version of SDDP.jl is landing: https://github.com/odow/SDDP.jl/pull/180

I'm not sure what will happen if you run `Pkg.update()` on Julia 0.6 after lands, so you might need to run
```julia
Pkg.checkout("SDDP", "release-v0")
```
to get the existing version.

Once the PR is merged, aAn upgrading guide will be available at 
https://odow.github.io/SDDP.jl/latest/upgrading_guide/

Until the PR is merged, the Kokako version is here: https://odow.github.io/Kokako.jl/latest/upgrading_guide/

Unfortunately, it looks like the upgrade will break most of your code 😢

**Comment by andrewrosemberg** [comment]
Finished on #4
