### ISSUE TITLE
Compatibility issues with new versions of JuMP/PowerModels/SDDP

### ISSUE THREAD

**Issue by csaiedu** [andrewrosemberg/HydroPowerModels.jl#45]
Hi

I am trying to learn about optimization of Hydro Power models using your package but the latest compatibility issues are causing havoc on your package and downgrading dependencies for SDDP/PowerModels etc...
Any chance your could have a go at upgrading the current version to latest compatibility?

Thanks

**Comment by andrewrosemberg** [comment]
Hi @csaiedu, sorry about that! Will have a look at it and try to fix it as soon as possible.

**Comment by andrewrosemberg** [comment]
Closing in favor of: https://github.com/andrewrosemberg/HydroPowerModels.jl/issues/47
This is being solved with the latest changes: https://github.com/andrewrosemberg/HydroPowerModels.jl/pull/50
