### ISSUE TITLE
Makes tests with bounds

### ISSUE THREAD

**Issue by Thuener** [andrewrosemberg/HydroPowerModels.jl#8]
Why did the value (12400) change? Is it because you run more iterations? (I can't guarantee that SDDP.jl is bug-free, so changes like this are worth investigating.)

_Originally posted by @odow in https://github.com/andrewrosemberg/HydroPowerModels.jl/pull/4_

**Comment by andrewrosemberg** [comment]
Solved in commit be77baef5e42b7f57eb7ec4fc5d65e0453a265f8
